// <auto-generated />
using InheritanceInEFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderingSystemAPI.Migrations
{
    [DbContext(typeof(FoodItemDbContext))]
    partial class FoodItemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InheritanceInEFCore.Models.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodItemId"));

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FoodItemId");

                    b.ToTable("FoodItems");

                    b.HasDiscriminator<string>("FoodType").HasValue("FoodItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InheritanceInEFCore.Models.Burger", b =>
                {
                    b.HasBaseType("InheritanceInEFCore.Models.FoodItem");

                    b.Property<bool>("HasCheese")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Burger");
                });

            modelBuilder.Entity("InheritanceInEFCore.Models.Pizza", b =>
                {
                    b.HasBaseType("InheritanceInEFCore.Models.FoodItem");

                    b.Property<int>("NumberOfToppings")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Pizza");
                });
#pragma warning restore 612, 618
        }
    }
}
